spring:  
  jpa:  
    hibernate:  
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect  
  datasource:  
    url: "jdbc:postgresql://localhost:5432/buenasnoches"  
    username: postgres 
    password: root
springdoc:
  swagger-ui:
    path: /swagger-ui.html
